# REF: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot
version: 2
updates:
  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
    reviewers: "peter.petrik"
    
  # Enable version updates for yarn
  - package-ecosystem: "yarn"
    # Look for `package.json` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
    reviewers: "peter.petrik"