
services:
  mm-docs:
    image: node:16-alpine
    restart: on-failure
    volumes:
      - .:/docs
    working_dir: "/docs"
    command: /bin/sh -c 'yarn install && yarn dev'
    ports:
      - 8080:8080