
services:
  mm-docs:
    image: node:20-alpine
    restart: on-failure
    volumes:
      - .:/docs
      - .src/.vitepress:/docs/src/.vitepress
    working_dir: "/docs"
    command: /bin/sh -c 'yarn install && yarn dev'
    ports:
      - 5173:5173