name: Build test
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
       cd docs
       yarn install
    - name: Generate
      run: |
        cd docs
        yarn generate