name: Build test
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Deps
      run: |
       yarn install
    - name: Generate Static Page
      run: |
        yarn build
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v2
      with:
        configPath: "./lighthouserc.json"
        temporaryPublicStorage: true