name: Status PROD

# runs 6:00 AM every day
on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  status_check:
    runs-on: ubuntu-latest
    env:
      URL: "https://merginmaps.com/docs"
    steps:
      - uses: actions/checkout@v3
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
           url: ${{ env.URL }}

      - name: Set variables
        run: |
          EXCLUDE_LIST=$(cat scripts/broken-link-exceptions.txt)
          echo "EXCLUDE_LIST=$EXCLUDE_LIST" >> $GITHUB_ENV

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: ${{ env.URL }}
          cmd_params: --buffer-size=8192 --max-connections-per-host=1 --color=always --skip-tls-verification --ignore-fragments --timeout=60 ${{ env.EXCLUDE_LIST }}
